//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenTK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ROOT count=&quot;2659&quot; length=&quot;55084&quot;&gt;
        ///  &lt;MEMBER slot=&quot;23&quot; start=&quot;431&quot; end=&quot;446&quot; name=&quot;glAttachShader&quot; /&gt;
        ///  &lt;MEMBER slot=&quot;24&quot; start=&quot;446&quot; end=&quot;470&quot; name=&quot;clCreateContextFromType&quot; /&gt;
        ///  &lt;MEMBER slot=&quot;40&quot; start=&quot;801&quot; end=&quot;822&quot; name=&quot;glBindAttribLocation&quot; /&gt;
        ///  &lt;MEMBER slot=&quot;42&quot; start=&quot;846&quot; end=&quot;859&quot; name=&quot;glBindBuffer&quot; /&gt;
        ///  &lt;MEMBER slot=&quot;82&quot; start=&quot;1666&quot; end=&quot;1684&quot; name=&quot;glBindVertexArray&quot; /&gt;
        ///  &lt;MEMBER slot=&quot;116&quot; start=&quot;2342&quot; end=&quot;2354&quot; name=&quot;glBlendFunc&quot; /&gt;
        ///  &lt;MEMBER slot=&quot;124&quot; start=&quot;2354&quot; end=&quot;2366&quot; name= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GLMembers {
            get {
                return ResourceManager.GetString("GLMembers", resourceCulture);
            }
        }
    }
}
